version: '2.1'
services:
    postgres:
        network_mode: "host"
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        network_mode: "host"
        image: concierge_airflow
        restart: always
        depends_on:
            - postgres
            - zeoserver
            - redis
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./configs:/usr/local/airflow/configs
            - ./scripts:/usr/local/airflow/scripts
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    redis:
        network_mode: "host"
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis

    zeoserver:
        network_mode: "host"
        volumes:
          - ./etc/zeo.conf:/plone/zeoserver/parts/zeoserver/etc/zeo.conf
        image: scandie/zeoserver:latest