---
version: 1
db:
 host:  "0.0.0.0"
 name:  "openprocurement"
 port: "5984"
 login: ""
 password: ""
 filter: "lots/status"
errors_doc: "broken_lots"

time_to_sleep:
  min: 5000
  max: 10000
  step: 1000
  heartbeat: false

lots_mapping:
  type: 'redis'
  host: 'localhost'
  port: '6379'

client_storage:
  host: 'localhost'
  port: 9100

lots:
  api:
    url: "http://0.0.0.0:6543"
    token: "concierge"
    version:  '2.3'
  types:
    loki:
      planned_pmt: [sellout.insider, sellout.english]
      aliases: [loki, yoke]
      assets:
        bounce: [bounce, domain]
    basic:
      aliases: [basic]
      assets:
        basic: [basic]
        compound: [compound]
        claimRights: [claimRights]

assets:
  api:
    url: "http://0.0.0.0:6543"
    token: "concierge"
    version:  '2.3'

auctions:
  api:
    url: "http://0.0.0.0:6543"
    token: "concierge"
    version:  '2.3'


formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console_concierge:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

loggers:
  openregistry.concierge.worker:
    handlers: [console_concierge]
    propagate: no
    level: DEBUG

  "":
    handlers: [console_concierge]
    level: DEBUG
